// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVIXBHHucPp5_HjWlxmbhEyaveVf25Tas',
    appId: '1:1078802987043:web:238df4f392eb96b5651996',
    messagingSenderId: '1078802987043',
    projectId: 'hamza-b15e3',
    authDomain: 'hamza-b15e3.firebaseapp.com',
    databaseURL: 'https://hamza-b15e3-default-rtdb.firebaseio.com',
    storageBucket: 'hamza-b15e3.appspot.com',
    measurementId: 'G-CY8CLJL34J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTnwQHvlYr_zRK9mYWVQNHJ_NqhuXW-kE',
    appId: '1:1078802987043:android:1d55840817913866651996',
    messagingSenderId: '1078802987043',
    projectId: 'hamza-b15e3',
    databaseURL: 'https://hamza-b15e3-default-rtdb.firebaseio.com',
    storageBucket: 'hamza-b15e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6X33t5sa66dW5F-utmHT7Eed66FlX_hw',
    appId: '1:1078802987043:ios:5150530b983481ca651996',
    messagingSenderId: '1078802987043',
    projectId: 'hamza-b15e3',
    databaseURL: 'https://hamza-b15e3-default-rtdb.firebaseio.com',
    storageBucket: 'hamza-b15e3.appspot.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6X33t5sa66dW5F-utmHT7Eed66FlX_hw',
    appId: '1:1078802987043:ios:a5771c50ab6c439d651996',
    messagingSenderId: '1078802987043',
    projectId: 'hamza-b15e3',
    databaseURL: 'https://hamza-b15e3-default-rtdb.firebaseio.com',
    storageBucket: 'hamza-b15e3.appspot.com',
    iosBundleId: 'com.example.firebaseExample.RunnerTests',
  );
}
